<?php

function easy_bots_full_list() {
    return [

        'bot',
        'crawl',
        'slurp',
        'spider',
        'crawler',
        'scanner',
        'fetch',
        'monitor',
        'scrapy',
        'Scrapy',
        'python',
        'curl',
        'wget',
        'Wget/',
        'axios',
        'httpclient',
        'http_request2',
        'java',
        'libwww',
        'perl',
        'go-http-client',
        'Go-http-client/',
        'node-superagent',
        'phpspider',
        'okhttp',
        'aiohttp',
        'aiohttp-client',
        'JetBrains IDE crawler',
        'httrack',
        'hts',
        'webcopier',


        // Grands moteurs de recherche
        'googlebot',
        'bingbot',
        'bingpreview',
        'adidxbot',
        'yandex',
        'baiduspider',
        'duckduckbot',
        'sogou',
        'Sogou web spider',
        'exabot',
        'facebot',
        'ia_archiver',
        'applebot',
        'seznambot',
        'qwantify',
        'mj12bot',
        'youdaobot',
        
        '360spider', 
        'haosouspider', 
        'sosospider',

        // Réseaux sociaux
        'facebookexternalhit',
        'twitterbot',
        'linkedinbot',
        'slackbot',
        'discordbot',
        'telegrambot',
        'skypeuripreview',
        'whatsapp',
        'viber',
        'pinterest',
        'redditbot',
        'tumblr',
        'nuzzel',
        'bitlybot',
        'vkshare',

        // Surveillance, cloud, etc...
        'amazonbot',
        'microsoftpreview',
        'msbot',
        'cloudflare', 
        'cloudflare-amp-fetcher',
        'cloudflare-health-check',
        'cloudflare-custom-hostname',
        'bushbaby',
        'chrome-ppp',
        'downtimedetector',
        'downnotifier.com',
        'gotmonitor',
        'hosttracker',
        'ips-agent',
        'miniflux',
        'monibot',
        'monitoring360bot',
        'monstabot',
        'nxbot',
        'pingomatic',
        'updown.io',
        'google-structured-data-testing-tool', 
        'turnitinbot', 
        'gobuster',
        'pricedroneshoppingbot',
        'urlcheckr',
        'watchmouse',
        'luminati',
        'brightdata',
        'oxylabs',
        'smartproxy',
        'proxycrawl',
        'scrapinghub',
        'scraperapi',
        'crawlera',
        'residential-proxy',

        // SEO, marketing, analyse
        'semrushbot',
        'ahrefsbot',
        'dotbot',
        'blexbot',
        'petalbot',
        'rogerbot',
        'linkdexbot',
        'screaming frog',
        'serpstatbot',
        'seokicks-robot',
        'sitecheckerbot',
        'netcraftsurveyagent',
        'dataforseo',
        'adsbot-google',
        'AdsBot-Google-Mobile',
        'crawlsonbot',
        'megaindex',
        'coccocbot',
        'seekport',
        'contentking',
        'uptime',
        'pingdom',
        'gtmetrix',
        'siteimprove',
        'domainstatsbot',
        'serpapi',
        'archivebot',
        'seznam',
        'metauri',
        'trendictionbot',
        'proxycurl',
        'linkpreview',
        'web-sniffer',
        'snowplow',
        'segmentbot',
        'keenbot',
        'quantcastbot',
        'domaincrawler',
        'trendkite',
        'riddler',
        'crawler4j',
        'robot',
        'seoscanners',
        'webmeup',
        'seekport bot',
        'sistrix',
        'openlinkprofiler',
        'searchmetricsbot',
        'majestic12',
        'backlinkcrawler',
        'ahrefssiteaudit',
        'barkrowler/1.0',
        'ScreamingFrogSEOSpider',


        // Archives et prévisualisation
        'archive.org_bot',
        'waybackarchive',
        'urlresolver',
        'pagepeeker',
        'webpreview',
        'outbrain',

        // Sécurité, analyse, pentest
        'zgrab',
        'nmap',
        'masscan',
        'shodan',
        'qualys',
        'censys',
        'wprecon',
        'wpscan',
        'sitelockspider',
        'acunetix',
        'netsparker',
        'censys.io crawler',
        'leakix bot',
        'SecurityTrails',
        'ZoomEye',
        'Hunter', 
        'DirBuster',
        'Dirsearch', 
        'whatweb',
        'Better Uptime',
        'Freshping',
        'Hexometer',
        'Pingometer',
        'Nodeping',
        'HetrixTools',
        'CalibreApp',
        'Catchpoint',
        'BrowserStack',
        'HeadlessChrome',
        'Playwright',
        'puppeteer',
        'ScreenerBot',
        'SEOkicks-Robot',
        'jaeles',
        'arachni',
        'metasploit',
        'crawler-joomscan',
        'nessusagent',
        'acunetix-standard',
        'netsparker-agent',
        'sqlmap',
        'hydra',
        'dirbuster/',
        'dirsearch/',
        'zaproxy',
        'burpcollaborator',
        'commix',
        'nikto scanner',
        'arachni-scanner',
        'wapiti',
        'crawler-joomscan',
        'scrapy/',
        'python-httplib',
        'mechanize',
        'requests',
        'httpx',
        'fetchbot',
        'axios/',
        'okhttp/',
        'got (node.js)',
        'node-fetch',



        // Bots IA
        'quora link preview',
        'NeevaBot',
        'QuivrBot',
        'KomoSearch',
        'komosearchbot',
        'WriterAIBot', 
        'KagiBot',
        'kagibot',
        'youchatbot',
        'BlackbirdBot',
        'yeti bot',
        'Yeti/1.0', 
        'metaphor',
        'metaphor-bot',
        'readwise', 
        'newsblur',
        'meta-externalagent/1.1',
        'FacebookBot/1.0',
        'gptbot', 
        'chatgpt-user', 
        'ChatGPT-User/1.0',
        'ChatGPT-User/2.0',
        'chatgpt-openai',
        'openai-embed',
        'openai-image',
        'GigaBot',
        'anthropic-ai',
        'ClaudeBot/1.0',
        'claude-web/1.0',
        'claudebot', 
        'duckassistbot', 
        'perplexitybot',
        'PerplexityBot/1.0',
        'Perplexity-User/1.0',
        'img2dataset', 
        'dingtalkbot',
        'MistralAI-User/1.0',
        'Google-Extended/1.0',
        'ccbot',
        'CCBot/1.0',
        'bytespider/1.0',
        'bytespider',
        'OAI-SearchBot',
        'cohere-ai/1.0',
        'AI2Bot/1.0',
        'Diffbot/0.1',
        'omgili/1.0',
        'YouBot',
        'Amazonbot/0.1',
        'applebot',
        'Applebot-Extended/1.0',
        'TimpiBot/0.8',
        'YisouSpider',
        'Barkrowler',
        'Bytespider-image',
        'ai-applied-ai-crawler',
        'huggingface',
        'midjourney',
        'nlpcloud',
        'anybot/',


        // AI chinoise
        'ernie bot',
        'qwen',
        'hunyuan',
        'doubao',
        'deepseek',
        'moonshot',
        'minimax',
        'zhipu',
        'modelscope',
        'baichuan',
        'pi.ai',
        'suno.ai',
        'magickpen',
        'yarn-ai',
        'openrouter.ai',
        'deepai',
        'modelscopebot',
        'openllm',


        //Suspects, spam, Ddos etc...
        'yandexbot',
        'mail.ru_bot',
        'zmap',
        'fofa',
        'python-requests',
        'python-urllib',
        'reqwest',
        'libwww-perl',
        'nessus',
        'paros',
        'nikto',
        'openvas',
        'virustotal',
        'semaltbot',
        'dataprovider spider',
        'sbl-bot',
        'mauibot',
        'alphabot',
        'NPBot',
        'Hotjar',
        'Mixpanel',
        'CrazyEgg',
        'FullStory',
        'inspectlet',
        'LuckyOrange',
        'Smartlook',
        'PlausibleBot', //tracking externe


        // Autres
        'uptimerobot',
        'uptimia',
        'datadog',
        'statuscake',
        'newrelicpinger',
        'hubspot',
        'mailchimp',
        'clicky',
        'pingdom.com bot',
        'site24x7',
        'downnotifier',
        'check-host',
        'ghostinspector',
        'calibreapp',
        'loader.io',
        'webpage-test',
        'googleweblight',
        'speedcurve',
        'dotcom-monitor',
        'uptimebot',
    ];
}

